#General
frame_timing=0
toggle_logging=0
position=top-right
no_display

#GPU
gpu_temp
gpu_core_clock
gpu_power
gpu_color=76B900

#CPU
cpu_temp
cpu_mhz
cpu_power
cpu_color=ED1C24

#VRAM
vram
vram_color=E6E6FA
